name: Deploy to Both Platforms

on:
  push:
    branches:
      - main  # 监听 main 分支推送

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout
        uses: actions/checkout@v4

      # 安装 Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      # 构建 GitHub Pages 版本（显式注入环境变量）
      - name: Build for GitHub Pages
        run: hugo -D
        env:
          HUGO_BASEURL: ${{ secrets.GH_PAGES_BASEURL }}  # 你的 GitHub Pages 域名

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./public
          commit_message: "Deploy to GitHub Pages"

      # 无需额外步骤部署 Cloudflare Pages，它会自动从仓库构建
